name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deployHML:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    environment: Homolog

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move deploy files
        run: cp deploy/discloud/discloud.dev.config ./discloud.config

      - name: Zip project
        run: |
          zip -r bot.zip \
          package.json \
          package-lock.json \
          dist/* \
          discloud.config \
          .env \
          -x "*.git*" "*.github*" "node_modules/*"

      - name: Clear Discloud App
        env:
          DISCLOUD_API_KEY: ${{ secrets.DISCLOUD_API_KEY }}
        run: |
          curl -X DELETE "https://discloud.app/api/v2/app/YOUR_APP_ID" \
          -H "api-token: $DISCLOUD_API_KEY"

      - name: Deploy to Discloud (Homolog)
        env:
          DISCLOUD_API_KEY: ${{ secrets.DISCLOUD_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          SKIP_COMMAND_CREATION: ${{ vars.SKIP_COMMAND_CREATION }}
          SKIP_COMMAND_DELETION: ${{ vars.SKIP_COMMAND_DELETION }}
          VERSION: ${{ vars.VERSION }}
          ENV: ${{ vars.ENV }}
        run: |
          curl -X POST "https://discloud.app/api/v2/app/upload" \
          -H "api-token: $DISCLOUD_API_KEY" \
          -F "file=@bot.zip"
