name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deployHML:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    environment: Homolog

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move deploy files
        run: cp deploy/discloud/discloud.dev.config ./discloud.config

      - name: Zip project
        run: |
          zip -r bot.zip \
          package.json \
          package-lock.json \
          dist/* \
          discloud.config \
          .env \
          -x "*.git*" "*.github*" "node_modules/*"

      - name: Deploy to Discloud (Homolog)
        env:
          DISCLOUD_API_KEY: ${{ secrets.DISCLOUD_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

          DEV_MODE: ${{ vars.DEV_MODE }}
          DISCORD_DEV_MODE_USER: ${{ vars.DISCORD_DEV_MODE_USER }}
          DISCLOUD_APP_ID: ${{ vars.DISCLOUD_APP_ID }}
          VERSION: ${{ vars.VERSION }}
          ENV: ${{ vars.ENV }}
        run: |
          curl -X "PUT" \
          "https://api.discloud.app/v2/app/$DISCLOUD_APP_ID/commit" \
          -H "accept: */*" \
          -H "api-token: $DISCLOUD_API_KEY" \
          -H "Content-Type: multipart/form-data" \
          -F "file=@bot.zip;type=application/x-zip-compressed"
